rough in drizzle.  Works for --pg, fails for --sqlite3:
src/server.ts:26:16 - error TS2339: Property 'length' does not exist on type 'SQLiteSelect<"welcome", "sync", void, { count: SQLiteInteger<{ tableName: "welcome"; name: "count"; data: number; driverParam: number; hasDefault: false; notNull: true; }>; }, "single", Record<...>>'.

26   if (welcome?.length > 0) {
                  ~~~~~~

src/server.ts:27:13 - error TS7053: Element implicitly has an 'any' type because expression of type '0' can't be used to index type 'SQLiteSelect<"welcome", "sync", void, { count: SQLiteInteger<{ tableName: "welcome"; name: "count"; data: number; driverParam: number; hasDefault: false; notNull: true; }>; }, "single", Record<...>>'.
  Property '0' does not exist on type 'SQLiteSelect<"welcome", "sync", void, { count: SQLiteInteger<{ tableName: "welcome"; name: "count"; data: number; driverParam: number; hasDefault: false; notNull: true; }>; }, "single", Record<...>>'.

27     count = welcome[0].count + 1;
               ~~~~~~~~~~